version: "3"
volumes:
  shuttle-gateway-vol:
    name: shuttle-gateway-vol
networks:
  shuttle-user-net:
    name: shuttle-user-net
services:
  gateway:
    image: "${CONTAINER_REGISTRY}/gateway:${BACKEND_TAG}"
    depends_on:
      - provisioner
    ports:
      - 8000:8000
      - 8001:8001
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname==controller
    networks:
      shuttle-user-net:
    volumes:
      - shuttle-gateway-vol:/var/lib/shuttle
      # This image needs to run highly privileged in order to
      # orchestrate user runtimes safely
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RUST_LOG=${RUST_LOG}
    command:
      - "--control=0.0.0.0:8001"
      - "--user=0.0.0.0:8000"
      - "--image=${CONTAINER_REGISTRY}/deployer:${BACKEND_TAG}"
      - "--prefix=shuttle_"
      - "--network-name=shuttle-user-net"
      - "--provisioner-host=provisioner"
      - "--state=/var/lib/shuttle/gateway.sqlite"
  provisioner:
    image: "${CONTAINER_REGISTRY}/provisioner:${PROVISIONER_TAG}"
    depends_on:
      - pg
      - mongodb
    environment:
      - RUST_LOG=${RUST_LOG}
    networks:
      shuttle-user-net:
    command:
      - "--ip=0.0.0.0"
      - "--port=8000"
      - "--shared-pg-uri=postgres://postgres:${POSTGRES_PASSWORD}@pg:5432/postgres"
      - "--shared-mongodb-uri=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin"
      - "--internal-mongodb-address=mongodb"
      - "--internal-pg-address=pg"
      - "--fqdn=${DB_FQDN}"
  pg:
    image: "${CONTAINER_REGISTRY}/postgres:${POSTGRES_TAG}"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      shuttle-user-net:
    ports:
      - 8002:8000
      - 5432:5432
    deploy:
      placement:
        constraints:
          - node.hostname==postgres
  mongodb:
    image: mongo:5.0.10
    restart: always
    networks:
      shuttle-user-net:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    deploy:
      placement:
        constraints:
          - node.hostname==postgres
